# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MKAbuMattar.Sarab
PackageVersion: 0.0.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.18362.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Sarab
ReleaseDate: 2026-10-02
AppsAndFeaturesEntries:
- DisplayName: Sarab
  Publisher: Sarab
  DisplayVersion: 0.0.3
  ProductCode: Sarab
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/MKAbuMattar/sarab/releases/download/v0.0.3/Sarab_0.0.3_x64-setup.exe
  InstallerSha256: 77A9C2163FB0FEB6B244D3373C31CBB3C281E80C0824D9C157980889AB8749D7
ManifestType: installer
ManifestVersion: 1.12.0
